- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Upgrade distribution
    apt: update_cache=yes upgrade=yes cache_valid_time=1800

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install base packages
    apt: pkg={{ item }} state=latest
    with_items:
      - vim
      - zsh
      - git
      - zsh
      - fzf
      
  - name: Make zsh default bash
    shell: chsh -s $(which zsh)
    become: true
  
  - name: Install required system packages
    apt: pkg={{ item }} state=latest update_cache=yes
    with_items: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/debian stretch stable
      state: present

  - name: Update apt and install docker-ce docker-ce-cli containerd.io
    apt: pkg={{ item }} state=latest update_cache=yes
    with_items: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
